//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProgrammingTricks.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Trick
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Trick()
        {
            this.Comments = new HashSet<Comment>();
        }
    
        public System.Guid TricksId { get; set; }
        public string Title { get; set; }
        public string TrickContent { get; set; }
        public string AuthorId { get; set; }
        public Nullable<System.Guid> Language { get; set; }
        public System.DateTime UploadDate { get; set; }
        public string Description { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Comment> Comments { get; set; }
    }
}
